# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x08keywords\"\"\n\x0eKeywordRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"#\n\x0fKeywordResponse\x12\x10\n\x08keywords\x18\x01 \x03(\t2Z\n\x10KeywordExtractor\x12\x46\n\x0f\x45xtractKeywords\x12\x18.keywords.KeywordRequest\x1a\x19.keywords.KeywordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYWORDREQUEST']._serialized_start=26
  _globals['_KEYWORDREQUEST']._serialized_end=60
  _globals['_KEYWORDRESPONSE']._serialized_start=62
  _globals['_KEYWORDRESPONSE']._serialized_end=97
  _globals['_KEYWORDEXTRACTOR']._serialized_start=99
  _globals['_KEYWORDEXTRACTOR']._serialized_end=189
# @@protoc_insertion_point(module_scope)
